In [1]:
import  numpy as np

In [2]:
data=np.random.randint(0,10,(3,3))

In [3]:
data

array([[4, 3, 4],
       [2, 0, 4],
       [4, 7, 2]])

In [5]:
data.sum()

np.int64(30)

In [6]:
data.sum(axis=1) ##row level addition

array([11,  6, 13])

In [7]:
data.sum(axis=0) ##column level addition

array([10, 10, 10])

In [8]:
data.max()

np.int64(7)

In [9]:
data.min()

np.int64(0)

In [11]:
data

array([[4, 3, 4],
       [2, 0, 4],
       [4, 7, 2]])

In [10]:
data.max(axis=1)

array([4, 4, 7])

In [12]:
data.max(axis=0)

array([4, 7, 4])

In [17]:
data.argmax(axis=1)

array([0, 2, 1])

In [15]:
data

array([[4, 3, 4],
       [2, 0, 4],
       [4, 7, 2]])

In [18]:
data.argmax(axis=0)

array([0, 2, 0])

In [19]:
data=np.random.randint(0,10,(5,5))

In [20]:
data      ##10 stores and 5 product level sales

array([[0, 8, 2, 0, 9],
       [9, 9, 1, 7, 8],
       [9, 4, 5, 6, 1],
       [5, 9, 5, 2, 0],
       [9, 8, 5, 4, 5]])

In [21]:
data.sum(axis=1)

array([19, 34, 25, 21, 31])

In [23]:
data.sum(axis=0)

array([32, 38, 18, 19, 23])

In [ ]:
## what is the lowest product sales in  store 1

In [26]:
data.sum(axis=1).argmin()+1

np.int64(1)

In [27]:
data.sum()

np.int64(130)

In [28]:
data=np.random.randint(10,100,(10,5))

In [29]:
data

array([[44, 10, 11, 95, 55],
       [81, 47, 59, 91, 84],
       [52, 85, 84, 24, 83],
       [38, 73, 92, 45, 81],
       [46, 75, 45, 66, 58],
       [38, 48, 22, 84, 24],
       [22, 10, 37, 84, 37],
       [38, 99, 13, 64, 86],
       [78, 72, 34, 28, 10],
       [13, 41, 17, 47, 72]])

In [30]:
data.sum(axis=0)[3:].sum()

np.int64(1218)

In [32]:
data[:,3:5].sum()

np.int64(1218)

In [33]:
data

array([[44, 10, 11, 95, 55],
       [81, 47, 59, 91, 84],
       [52, 85, 84, 24, 83],
       [38, 73, 92, 45, 81],
       [46, 75, 45, 66, 58],
       [38, 48, 22, 84, 24],
       [22, 10, 37, 84, 37],
       [38, 99, 13, 64, 86],
       [78, 72, 34, 28, 10],
       [13, 41, 17, 47, 72]])

In [34]:
data.sum(axis=0).max()

np.int64(628)

In [35]:
data.sum(axis=1).min()

np.int64(190)

In [36]:
data.sum(axis=0).max()-data.sum(axis=1).min()

np.int64(438)

In [37]:
data=np.random.randint(0,10,10)

In [38]:
data

array([2, 4, 1, 2, 9, 0, 9, 3, 0, 7])

In [39]:
data.mean()

np.float64(3.7)

In [42]:
np.median(data)

np.float64(2.5)

In [45]:
np.quantile(data,0.25)

np.float64(1.25)

In [46]:
np.quantile(data,0.75)

np.float64(6.25)

In [47]:
np.quantile(data,0.5)

np.float64(2.5)

In [48]:
np.median(data)

np.float64(2.5)

In [ ]:
###
##descriptive statastics
##mean,median,max,min,range,q1,q3,iqr,std,var

In [49]:
data

array([2, 4, 1, 2, 9, 0, 9, 3, 0, 7])

In [50]:
np.std(data)## standard deviation

np.float64(3.287856444554719)

In [51]:
np.var(data) ##Variance

np.float64(10.809999999999999)

In [52]:
data=np.random.randint(0,10,(10,2))

In [53]:
data

array([[5, 6],
       [7, 1],
       [6, 2],
       [5, 2],
       [5, 7],
       [9, 7],
       [3, 6],
       [9, 5],
       [3, 4],
       [0, 5]])

In [54]:
np.corrcoef(data.T) ## correlation Coefficient(trnspose)

array([[ 1.        , -0.03677316],
       [-0.03677316,  1.        ]])

In [55]:
v1=np.arange(1,11)

In [56]:
v2=np.arange(10,20)

In [57]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
data[:,0]=v1
data[:,1]=v2

In [60]:
np.corrcoef(data.T)

array([[1., 1.],
       [1., 1.]])

In [66]:
data=np.random.randint(0,10,(5,5))

In [68]:
np.corrcoef(data)

array([[ 1.        ,  0.22258705, -0.02376242, -0.55748227,  0.28552012],
       [ 0.22258705,  1.        , -0.15640942, -0.20081673,  0.90487483],
       [-0.02376242, -0.15640942,  1.        ,  0.67758079,  0.        ],
       [-0.55748227, -0.20081673,  0.67758079,  1.        , -0.32784764],
       [ 0.28552012,  0.90487483,  0.        , -0.32784764,  1.        ]])